### PR TITLE
feat: added basic game menu

### PR DESCRIPTION
**Pull request by stravo1**
changed css styes
added difficulty selection which changes the rock generation and rock movement speed
added game-over screen

(whatever i could do in an hour :) )

### CODE REVIEW

**Comment by stravo1** [comment]
> changed css styes added difficulty selection which changes the rock generation and rock movement speed added game-over screen
> 
> (whatever i could do in an hour :) )

screenshots:
Screen Shot 2022-01-27 at 10 01 48
Screen Shot 2022-01-27 at 10 01 54
Screen Shot 2022-01-27 at 10 02 22
Screen Shot 2022-01-27 at 10 02 27

**Comment by sharanya-mitra** [comment]
wow it looking cool thanks for contributing

**Comment by sharanya-mitra** [comment]
but why you don't make separate branch

**Comment by stravo1** [comment]
> but why you don't make separate branch

i created the branch in my fork, i can't directly make branches on your repo 😅
anyways you have merge it to the master branch at the end of the day

**Comment by sharanya-mitra** [comment]
oh my bad I unseen that

**Pull request merged**
